version: "3.8"

services: 
  personal_front_end:
    container_name: personal_front_end
    build: ./front-end
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm i && npm run dev"
    volumes:
      - ./front-end:/front-end
    ports:
      - 3001:3001
