source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.4"

gem "rails", "~> 7.0.4", ">= 7.0.4.2"

gem "pg", "~> 1.1"
gem 'devise', '~> 4.2'
gem 'devise-jwt'
gem 'rack-cors'
gem "puma", "~> 5.0"
gem 'byebug', '~> 9.0', '>= 9.0.6'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false


group :development, :test do

  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
end

